name: Deno Publish

on:
  push:
    branches:
      - main  # Vous pouvez changer cela si vous utilisez une autre branche pour la publication
    tags:
      - 'v*'  # Déclenche la publication uniquement lors de la création d'un tag, par exemple "v1.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.30.0  # Assurez-vous de spécifier la version de Deno que vous souhaitez utiliser

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Run tests (optionnel)
        run: deno test

      - name: Publish module to deno.land
        run: |
          deno publish https://deno.land/x/@insu_qg/mots/mod.ts  # Remplacez par l'URL correcte de votre module
        env:
          DENO_TOKEN: ${{ secrets.DENO_TOKEN }}
